services:
  gitmirror:
    build:
      context: .
      dockerfile: GitMirror.Docker/dockerfile
    ports:
      - 5000:5000
    environment:
      - GitPlatforms__AzureDevOps__BaseUrl=https://your-organization.visualstudio.com/
      - GitPlatforms__AzureDevOps__Username=username
      - GitPlatforms__AzureDevOps__Password=placeholder
      - GitPlatforms__GitLab__BaseUrl=https://gitlab.your-organization.com/
      - GitPlatforms__GitLab__Username=username
      - GitPlatforms__GitLab__Password=placeholder
    networks:
      - gitmirror_network

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - gitmirror_network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    networks:
      - gitmirror_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - gitmirror_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.1
    ports:
      - 5044:5044
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - gitmirror_network

networks:
  gitmirror_network:
    driver: bridge
