namespace: gitmirror
connectionstrings:
  postgres: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;"
elastic:
  tcpsink: "tcp://127.0.0.1:5044"
hangfire:
  username: "admin"
  password: "admin"
