apiVersion: v1
kind: Secret
metadata:
  name: gitmirror-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  GitPlatforms__AzureDevOps__BaseUrl: {{ .Values.gitplatforms.azuredevops.baseurl | b64enc  }}
  GitPlatforms__AzureDevOps__Username: {{ .Values.gitplatforms.azuredevops.username | b64enc  }}
  GitPlatforms__AzureDevOps__Password: {{ .Values.gitplatforms.azuredevops.password | b64enc  }}
  GitPlatforms__GitLab__BaseUrl: {{ .Values.gitplatforms.gitlab.baseurl | b64enc  }}
  GitPlatforms__GitLab__Username: {{ .Values.gitplatforms.gitlab.username | b64enc  }}
  GitPlatforms__GitLab__Password: {{ .Values.gitplatforms.gitlab.password | b64enc  }}