apiVersion: v1
kind: Service
metadata:
  name: gitmirror-service
  namespace: {{ .Values.namespace }}
  labels:
    app: gitmirror-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32111
  selector:
    app: gitmirror-deployment