apiVersion: v1
kind: Secret
metadata:
  name: gitmirror-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ConnectionStrings__Postgres: {{ .Values.connectionstrings.postgres | b64enc }}
  Elastic__TcpSink: {{ .Values.elastic.tcpsink | b64enc }}
  Hangfire__Username: {{ .Values.hangfire.username | b64enc }}
  Hangfire__Password: {{ .Values.hangfire.password | b64enc }}