FROM node:24 AS angular-build
WORKDIR /app
COPY ./GitMirror.UI ./GitMirror.UI
WORKDIR /app/GitMirror.UI
# RUN npm ci --Temporarily disabled, but needs to be enabled for security reasons.
RUN npm install
RUN npm audit
RUN npm run build --omit=dev

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dotnet-build
WORKDIR /src
COPY ./GitMirror.API .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*
COPY --from=angular-build /app/GitMirror.UI/dist /app/wwwroot
COPY --from=dotnet-build /app/publish .

EXPOSE 5000
ENTRYPOINT ["dotnet", "GitMirror.API.dll"]